# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

description = "A minimal, simple, and responsive academic page based on Avicenna by Hadi Sinaee (https://hadisinaee.github.io/)."
features = ["Academic", "Responsive", "Clean And Minimal", "Social Media Links"]
homepage = "https://github.com/fzenke/sarrancenia-hugo"
license = "MIT"
licenselink = "https://github.com/fzenke/sarrancenia-hugo/blob/master/LICENSE"
min_version = "0.41"
name = "Sarrancenia"
tags = ["academic", "personal", "minimal", "minimalist", "clean", "responsive", "simple", "university"]

[author]
homepage = "https://fzenke.net"
name = "Friedemann Zenke"
